### ISSUE TITLE
Standing near the Wall to one side of the Sniper Walkway on Viaduct renders weapons nearly black

### ISSUE THREAD

**Issue by martyTF** [AmperSoftware/TF-Source-2#10]
### Describe the bug

Standing near the Wall to one side of the Sniper Walkway on Viaduct renders weapons nearly black. See attached images. Applies to all classes, only found that bug on that map in that spot, so probably map related, dunno.

### To Reproduce

1. Stand close to the Wall to one side of the Sniper Walkway on Viaduct
2. Watch arms/hands rendered very very dark and weapons nearly black.

### Expected behavior

Normal lighting

### Media/Files

![image](https://user-images.githubusercontent.com/69526651/186503317-7f774ffe-2b03-4d88-b148-8a694e17a443.png)
![image](https://user-images.githubusercontent.com/69526651/186503691-cdc08aeb-a371-473c-b94b-a507df30aef5.png)
![image](https://user-images.githubusercontent.com/69526651/186503831-6f41bd37-2201-420f-908a-25453c6c9899.png)

**Comment by KayaDLX** [comment]
This is probably fixed or will be on a next compile, it's just a regular lightprobe issue.
