### ISSUE TITLE
Various control point UI issues

### ISSUE THREAD

**Issue by DrakeFruit** [AmperSoftware/TF-Source-2#115]
### Describe the bug

When a **red** player captures the point, there is a sliver of whatever team had the point before on the right side of the UI right before it is captured.

Also the capture timer does not work for either teams after the first capture.

### To Reproduce

Capture the point on red team as any class.

### Expected behavior

The UI should be fully red, and not show the color behind it right before capture.
The capture timer should slowly change colors as intended.

### Media/Files

https://user-images.githubusercontent.com/94070205/235318676-872c65a8-76c0-4520-add1-f21906886922.mp4

**Comment by Retr0-01** [comment]
Merged with #117
