### ISSUE TITLE
Point can be captured before available

### ISSUE THREAD

**Issue by DrakeFruit** [AmperSoftware/TF-Source-2#116]
### Describe the bug

The control point can be captured before the timer has reached 0
This can be fixed by adding "& !Locked":
![image](https://user-images.githubusercontent.com/94070205/235319628-6a411485-70f6-4056-970e-31919f1029f1.png)

### To Reproduce

stand on the capture point before the round has started

### Expected behavior

You should not be able to capture the point until the timer has reached 0

### Media/Files

https://user-images.githubusercontent.com/94070205/235319669-f81497bc-3996-40b4-86d2-311464deb3d4.mp4

**Comment by badandbest** [comment]
In Team Fortress 2, the point is locked for 30 seconds to let everyone to get to mid.

https://github.com/AmperSoftware/TF-Source-2/assets/91832803/d7794911-3c6c-45d5-8f43-96db1620ac8d

I believe what DrakeFruit was trying to demonstrate is that the control point can be captured while it's locked. Funnily enough it still says "No capturing at this time."

https://github.com/AmperSoftware/TF-Source-2/assets/91832803/8db18d02-a6eb-4b2a-9ccc-b33d310068a0
