### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by badandbest** [AmperSoftware/TF-Source-2#117]
Tested on https://github.com/AmperSoftware/TF-Source-2/commit/1f17ac03b353931ecf261e8dd88405bcdb372d20. When the UI is updated I will update this issue alongside it.

<details><summary>

# TargetID ![](https://geps.dev/progress/100)

</summary>

> - [x] Missing button prompt texture for dropped weapons.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/6b4b415e-9c87-49c3-9e40-2f7679e7eae6)| ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/145166be-f760-4425-b92d-114ef7a0204f) | 

> - [x] Friendly Medics do not show their charge.
>
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/1cd673fb-9f87-4cf5-bf58-c4cd006dcc7e) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/ba169d87-7f17-4db1-b9d0-afd5a1e7e8f9) | 

</details>

<details><summary>

# Damage Numbers ![](https://geps.dev/progress/100)

</summary>

> - [x] Accumulative damage does not follow players.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/312dc9ed-bfa7-4206-b445-be40d354db68) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/ffff5c35-eb74-495a-a96a-cdfb952814dd) | 

> - [x] Damage info displays 0 damage.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/152dad77-4a47-481c-a004-02450aff34f7) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/179e70f4-0b1a-4adf-b631-13f08a24f86c) | 

</details>

<details><summary>

# Control Point ![](https://geps.dev/progress/66)

</summary>

> - [x] Capture progress is offset slightly to the left.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/4c9a8141-63f0-4551-ba21-a659c6545371) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/4040b3ba-3eb5-43b4-98af-867a41ac6746) | 

> - [x] Locked control points do not have a padlock.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/b4449c28-6144-4fb0-825f-22a166f2a05c) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/05326c2e-b1d4-4ffb-955e-d1ba35613cc1) | 

> - [ ] Progress circle doesn't fill up over time.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/6113ef05-625d-462e-8ee5-93d7ad22f45d) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/f24badcb-0d96-4b74-a0df-d4df627f52d4) | 

</details>

<details><summary>

# Capture The Flag ![](https://geps.dev/progress/100)

</summary>

> - [x] HUD does not point to where the intel is.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/b99632b8-73ae-4cf4-9140-c976d547a4bf) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/7e1b7e1b-a848-4b2e-81f3-69122d6eab7a) | 

</details>

<details><summary>

# Payload ![](https://geps.dev/progress/100)

</summary>

> - [x] HUD does not show how many is capturing.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/4e99f9a4-9fa4-432f-bff1-db6a189782c4) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/0529b8e4-a4d7-464d-9609-e894bf5a2967) | 

> - [x] Track is not shown.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/d9ba1fef-c600-422c-95e0-c7c6235e7127) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/6a99ab9b-a888-469f-a392-0e6f3138cb63) | 

> - [x] UI is not scaled right.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/ca22050f-b029-420f-a089-6c4216a61a41) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/bd115fc9-584a-4d4d-8632-4a5fa65a33f5) | 

> - [x] Points are not transparent.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/5606ce8f-ab2e-4852-8d68-43ff597969a0) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/b23e680c-3de3-49c4-89c5-7ae278280c16) | 

</details>

<details><summary>

# Killfeed ![](https://geps.dev/progress/100)

</summary>

> - [x] Blowing yourself up displays your name twice.
>
> | Current | Expected |
> |--------|--------|
> | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/a5db5414-8ca9-4158-8b79-aeb1db55ee1b) | ![](https://github.com/AmperSoftware/TF-Source-2/assets/91832803/39a33058-cda0-46d6-b5a8-f57f015fc8b9) | 

> - [x] Buildings killfeed
>
> Buildings don't have the correct killfeed icons.
> They also don't show up in the killfeed if destroyed by another player.

</details>

**Comment by qualitykk** [comment]
The payload HUD is like that because we havent even started to implement it btw, still good to be included here tho

**Comment by qualitykk** [comment]
So when does the padlock on control points not show up? Its working just fine on my end

**Comment by badandbest** [comment]
Updated for e459e18651e30fa9aa4c78023171e5b4d8701151

**Comment by Retr0-01** [comment]
Updated as of https://github.com/AmperSoftware/TF-Source-2/commit/1f17ac03b353931ecf261e8dd88405bcdb372d20
