### ISSUE TITLE
Taunting Thirdperson Weirdness

### ISSUE THREAD

**Issue by PixelNovaVT** [AmperSoftware/TF-Source-2#119]
### Describe the bug

When quickly pressing the taunt key to do a default taunt, it seems to (most of the time) just toggle thirdperson view.

### To Reproduce

Just quickly press the taunt key as any class.

### Expected behavior

Quickly pressing the taunt key should reliably and consistently trigger a taunt and not just put you in and out of thirdperson.

### Media/Files

https://github.com/AmperSoftware/TF-Source-2/assets/76824004/7e81742b-18c8-4e47-9bee-19b359debb8f

### Additional context

Deleted my download cache to ensure that I had a clean install of the latest TF:S2 version.

**Comment by badandbest** [comment]
Actually just press "G" once to enter third person.

**Comment by SeroRonin** [comment]
Yeah, there is a misplaced line of code that toggles the camera any time the taunt menu is opened, will look into removing it when I get the chance

**Comment by KayaDLX** [comment]
This was removed recently
