### ISSUE TITLE
If you switch weapon while firing flamethrower, flame loop sound will continue playing

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#124]
### Describe the bug

If you switch weapon while firing flamethrower, flame loop sound will continue playing

### To Reproduce

1. Use your flamethrower as Pyro
2. Switch weapon while holding fire
3. Notice the sound not stopping

### Expected behavior

Should stop on release

**Comment by Retr0-01** [comment]
Seems to be fixed @ latest ``dev``.
