### ISSUE TITLE
Heavy's fists' secondary fire animation repeating when M2 is held.

### ISSUE THREAD

**Issue by Herotroll** [AmperSoftware/TF-Source-2#14]
### Describe the bug

When the right mouse button is held while Heavy's fists are active, the attack animation keeps repeating from the start.

### To Reproduce

Simply go Heavy, equip the fists and hold M2.

### Expected behavior

https://user-images.githubusercontent.com/50330035/185809922-9ba8a57a-4cdf-4a42-8e2c-e7858f3fa0da.mp4

**Comment by Retr0-01** [comment]
Confirmed, this is fixed at latest `dev`
