### ISSUE TITLE
[SNIPER] You can zoom while reloading.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#15]
### Describe the bug

You can zoom while you are reloading the sniper rifle.

### To Reproduce

1. Shoot.
2. Scope while Sniper is reloading.

### Expected behavior

Sniper should not be able to zoom while reloading.

### Media/Files

https://user-images.githubusercontent.com/91832803/185359633-d7fc21cb-2ff8-4bc8-9309-946a3499fa78.mp4

**Comment by Retr0-01** [comment]
This is fixed @ latest `dev`
