### ISSUE TITLE
Charge-up sound for stickybomb launcher plays in full whenever you shoot it.

### ISSUE THREAD

**Issue by Yubbin** [AmperSoftware/TF-Source-2#159]
### Describe the bug

Whenever I shoot the stickybomb launcher, it makes the charge up sound as if i was holding left-click, even though I am not

### To Reproduce

select stickybomb launcher, quickly left click and do not hold. if you hold left click it seems to fix itself

### Expected behavior

the sound should stop playing when I let go of left click

**Comment by Retr0-01** [comment]
Duplicate of #123, closing.
