### ISSUE TITLE
[Pyro] Flamethrower does not replenish ammo from ammo packs

### ISSUE THREAD

**Issue by PixelNovaVT** [AmperSoftware/TF-Source-2#16]
### Describe the bug

The Flamethrower's ammo does not replenish from touching an ammo pack. Resupply works but not ammo packs.

### To Reproduce

1. Deplete the Flamethrower's ammo.
2. walk into an ammo pack.

### Expected behavior

The Flamethrower's ammo should be replenished when colliding with an ammo pack.

### Media/Files

![sf9uuWlwOr](https://user-images.githubusercontent.com/76824004/185288297-880dfde1-05e8-40ae-983d-71374ef47835.jpg)

**Comment by Retr0-01** [comment]
This was fixed in [PR #56](https://github.com/AmperSoftware/TF-Source-2/pull/56)
