### ISSUE TITLE
Getting killed while carrying a building makes you unable to place that building again

### ISSUE THREAD

**Issue by DrakeFruit** [AmperSoftware/TF-Source-2#173]
### Describe the bug

if you pick up a building and die, you can't place down the building again and the build menu says its already placed.

### To Reproduce

place down a building
pick it up
die
build menu says the building is already placed

### Expected behavior

should be able to build it again

### Media/Files

![image](https://github.com/AmperSoftware/TF-Source-2/assets/94070205/cc6a7371-657e-44b9-930c-965e72259a3d)

**Comment by qualitykk** [comment]
Should be fixed now
