### ISSUE TITLE
Invincible engineer buildings

### ISSUE THREAD

**Issue by DrakeFruit** [AmperSoftware/TF-Source-2#177]
### Describe the bug

Found a set of engineer buildings that didn't work and were completely invincible

### To Reproduce

I am unable to reproduce this, buildings worked fine the other 99% of the time, it was just this set of buildings.

### Expected behavior

the buildings should be destructable

### Media/Files

https://github.com/AmperSoftware/TF-Source-2/assets/94070205/8c47ee31-56ab-4df4-8353-b4c96830ff3b

**Comment by qualitykk** [comment]
Is this still happening?

**Comment by DrakeFruit** [comment]
I have no idea how to replicate it so I can't test if it is, sorry.

**Comment by qualitykk** [comment]
Cannot reproduce, feel free to reopen if you find a consistent setup to reproduce this issue.
