### ISSUE TITLE
Carrying intelligence blocks healing from certain angles

### ISSUE THREAD

**Issue by TheSpookiestUser** [AmperSoftware/TF-Source-2#189]
### Describe the bug

Teammates carrying the intelligence appear to break line-of-sight to the medigun from some angles, disconnecting the beam and preventing healing.  Hypothesis: the intelligence is being treated as a physical object and so blocks LOS?  May also affect being hit by enemies?

### To Reproduce

Attempt to heal a teammate carrying the intelligence. 

### Expected behavior

Medigun beam should not be disconnected by carrying the intelligence.

### Media/Files

https://i.imgur.com/JbiZqyG.mp4
https://i.imgur.com/EhVFXoO.mp4

### Additional context

Setting to not have to hold down m1 to maintain medigun beam was enabled.

**Comment by qualitykk** [comment]
Should be fixed in the latest version.
