### ISSUE TITLE
[PYRO] Syringes can be reflected.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#19]
### Describe the bug

You can reflect Medic's syringes as Pyro.

### To Reproduce

1. Get an enemy Medic to fire syringes at you.
2. Compression blast the syringes.

### Expected behavior

Syringes should not be reflectable.

### Media/Files

https://user-images.githubusercontent.com/91832803/185251114-5152ee43-2020-4f63-83a0-99128a4c8df8.mp4

**Comment by KayaDLX** [comment]
This is fixed
