### ISSUE TITLE
Chatbox closes after one frame. Making it impossible to chat.

### ISSUE THREAD

**Issue by badandbest** [AmperSoftware/TF-Source-2#199]
### Describe the bug

When I try to open the chatbox, it closes after one frame. Therefore making it impossible to chat.

### To Reproduce

Try to open chatbox.

### Expected behavior

The chatbox should stay open until you send a message or cancel.

### Media/Files

https://github.com/AmperSoftware/TF-Source-2/assets/91832803/8e19351c-2b5c-4bc0-920c-278afc2ff174

**Comment by Poganator** [comment]
Can confirm this happens to me as well

**Comment by Retr0-01** [comment]
Fixed in 3869c4947f41922136da9cef3eb37137d8ccf325
