### ISSUE TITLE
voice_menu 0/1/2 command should close the menu if ran again.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#21]
### What can't you do?

If voice_menu 0/1/2 is opened I cannot close it by pressing the bind again.

### How would you like it to work?

The menu should close if for example I press the bind to open voice_menu 0 when voice_menu 0 is already opened.

### What have you tried?

You can close the menu by running a voice command. It really isn't the end of the world.

**Comment by Retr0-01** [comment]
This was fixed in [PR #52](https://github.com/AmperSoftware/TF-Source-2/pull/52)
