### ISSUE TITLE
Stickies collide with skybox

### ISSUE THREAD

**Issue by scroobert** [AmperSoftware/TF-Source-2#26]
### Describe the bug

Demoman's sticky bombs are able to stick to the walls of the skybox

### To Reproduce

1. Pick demoman
2. Shoot at the skybox
3. Profit

### Expected behavior

Sticky bombs should bounce off the skybox

### Media/Files

![image](https://user-images.githubusercontent.com/110732290/184637740-e005c6a2-5561-44bf-be25-dad214103b9e.png)

**Comment by KayaDLX** [comment]
This will be fixed on the next backend upload.
