### ISSUE TITLE
Auto Reload doesn't work

### ISSUE THREAD

**Issue by MeDerpWasTaken** [AmperSoftware/TF-Source-2#31]
### Describe the bug

Auto-reload doesn't work, despite being enabled in settings.

### To Reproduce

1. Enable auto-reload in settings
2. Fire gun
3. Wait for it to auto-reload (it doesn't)

### Expected behavior

When auto-reload is enabled in settings, your weapon should automatically reload when the clip isn't full and you have enough reserve ammo.

### Media/Files

https://user-images.githubusercontent.com/62511835/182035829-51c50f09-932e-46a5-b0d5-492f49220c29.mp4

**Comment by KayaDLX** [comment]
Options currently work, only the animation still plays for auto reload.

**Comment by MeDerpWasTaken** [comment]
It seems to be working now
