### ISSUE TITLE
Slight delay before reloading

### ISSUE THREAD

**Issue by googleooer** [AmperSoftware/TF-Source-2#38]
**Describe the bug**
There seems to be a short delay before reloading.

**To Reproduce**
1. Fire a weapon
2. Reload
3. Observe

**Expected behavior**
It should behave like reloading in normal Team Fortress 2

**Screenshots**
Here's a comparison between TF2 and TF2 S2.

Syringe gun
TF2: https://streamable.com/n05k9e
TF2 S2: https://streamable.com/ii0qh3

Scattergun
TF2: https://streamable.com/wcj2mi
TF2 S2: https://streamable.com/91ecjs

Stickybomb Launcher:
TF2: https://streamable.com/xcb7x2
TF2 S2: https://streamable.com/zoczi6

**Additional context**
Could be related to  AmperSoftware/TF-Source-2#46? Maybe the firing speeds being wrong makes it feel like there's a delay before reloading.

**Comment by yourbadandimbest** [comment]
This is fixed.
