### ISSUE TITLE
Spawn points make players spawn at random angles

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#39]
**Describe the bug**
Spawn points don't spawn players in the correct angle set in Hammer, often spawning players in the wrong direction.

**To Reproduce**
1. Place a spawn point in Hammer
2. Spawn with TF:S2 gamemode
3. You won't spawn in the correct angle

**Expected behavior**
Should always use the same angle for every spawn points rather than the current camera angle.

**Comment by Retr0-01** [comment]
@MoonlyDays Can you look into this when you get a chance? I have checked all the related code in our SDK and I see what is wrong with it.
