### ISSUE TITLE
Charge meters & metal counter won't hide with scoreboard

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#40]
**Describe the bug**
Those meters will not stop displaying if we bring up the scoreboard.

**To Reproduce**
1. Go Engineer/Demo
2. Press Tab
3. Meters will still display

**Expected behavior**
Should hide themselves

**Screenshots**
![image](https://user-images.githubusercontent.com/67245359/162448799-157ac961-c958-4927-a652-18afad0546c2.png)

**Comment by Retr0-01** [comment]
Closing as being outdated and partially fixed.

Engineer has currently no metal display and demo's charging bar is below the ammo count which gets hidden.
