### ISSUE TITLE
Bullets deal no damage in some situations

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2#45]
**Describe the bug**
Please look at the video demonstration down below.

**To Reproduce**
1. Map used for this test is test/scale
2. Players near/inside of each other block/absorb/inferfere with bullet collisions

**Expected behavior**
Shot from every angle should damage the enemy player unless clearly absorbed by a friendly player.

**Additional context**
2 enemy scouts are spawned inside each other on a non TFS2 map, blue scout, mid jump, gets stuck in those 2 scouts. Almost no shots hit any of the 2 red scouts.

https://user-images.githubusercontent.com/41569944/162083343-f9b61aca-5470-4457-8ccd-d1ebdca96f93.mp4

**Comment by Retr0-01** [comment]
Is there any other class/case in which you have encountered this? @uglycoal

**Comment by Retr0-01** [comment]
Closing in favour of #29
