### ISSUE TITLE
Let us set respawn time in server settings.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#5]
### What can't you do?

When playtesting it is very annoying to have to wait for the respawn timer. Instant respawning would be very convenient but unfortunately it is not an option when setting up a lobby.

### How would you like it to work?

A slider or button in server settings that either controls the respawn time or removes it altogether.

### What have you tried?

Typing respawn in console is a workaround but
1. Not everyone knows about the respawn command.
2. Faster respawn would be a good quality of life feature all around. Especially for playtesting.

**Comment by qualitykk** [comment]
This has been added into dev branch and should become available once its been uploaded to the backend, once dev gets merged into main and uploaded and it works feel free to close this issue.
