### ISSUE TITLE
Last blog post on main menu is outdated

### ISSUE THREAD

**Issue by qualitykk** [AmperSoftware/TF-Source-2#53]
### Describe the bug

Currently the last blogpost on the Q (Main) Menu shows the Tinker and Timber blogpost and not the latest one.

### To Reproduce

1. Open the main menu (q)
2. Look at the latest blog post

### Expected behavior

The blog post should be the latest (Opening the Source) one

**Comment by Retr0-01** [comment]
I'll be taking this over since it's quite a simple fix, are you ok with this @KayaDLX ?
