### ISSUE TITLE
Rockets are unaffected by rampup and falloff.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#60]
### Describe the bug

When I land a direct hit with a rocket it does the same flat damage at all distances.

### To Reproduce

1. Fire a rocket directly at a player.
2. Repeat further away.

### Expected behavior

Rocket damage should scale appropriately with distance.

### Media/Files

https://user-images.githubusercontent.com/91832803/205445204-d93d67fa-48dc-4636-8b0c-efb9cacf68be.mp4

https://user-images.githubusercontent.com/91832803/205445295-2ea50f9c-85cd-42d1-a44a-7a9b5c4be0f3.mp4

**Comment by Retr0-01** [comment]
Fixed at 25e036f103d1adac7f4be27031c277226c5e7a7b
