### ISSUE TITLE
"Object refrence not set to an instance of an object" Error

### ISSUE THREAD

**Issue by SlincHD** [AmperSoftware/TF-Source-2#63]
### Describe the bug

when i try to load in to a game of tf2s2 i see a square with missing textures, sometimes a map behind it and on the bottom left it says "Object refrence not set to an instance of an object"

### To Reproduce

start a server in tfs2, and after you selectet someone and load in to the map this happends

### Expected behavior

loading in the the map and beaing able to play

### Media/Files

![image](https://user-images.githubusercontent.com/85231739/212972316-6d532478-f4ee-4356-93ff-3c8f1b6de1ee.png)
happends on every map i checked

**Comment by qualitykk** [comment]
This should have been fixed in the latest set of commits and be on the backend, if loading into the map works for you feel free to close this issue.

**Comment by SlincHD** [comment]
![Uploading image.png…]()
well it works
