### ISSUE TITLE
More options for tf_item_teamflag

### ISSUE THREAD

**Issue by PixelNovaVT** [AmperSoftware/TF-Source-2#64]
### What can't you do?

The flag entity seems quite limited compared to the one in live TF2, mainly that it's not as customizable as live TF2's.

### How would you like it to work?

These are the options present in live TF2's item_teamflag that I think tf_item_teamflag should have:

- Model
- HUD Icon (maybe)
- "Paper" Particle
- Trail Effect
- Use Trail Effect
- Visible When Disabled

Also while these are not in Live TF2 I think there should also be a Color value option.

Though if there is a specific reason you guys don't want to add these options or can't, it's understandable.

**Comment by yourbadandimbest** [comment]
Good idea. I'll work on that for you.

**Comment by Retr0-01** [comment]
Implemented in #65
