### ISSUE TITLE
Projectiles don't render anymore

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#67]
### Describe the bug

Whenever you fire a projectile type weapon, the projectiles do not draw at all.

### To Reproduce

1. Play Medic, Demoman or Soldier
2. Fire your weapon
3. Notice them missing

### Expected behavior

Should draw as expected, this probably broke during recent pain days.

**Comment by yourbadandimbest** [comment]
I found the cause and am working on it

**Comment by yourbadandimbest** [comment]
Should be fixed in the latest version
