### ISSUE TITLE
Screen overlay shaders do not render

### ISSUE THREAD

**Issue by KayaDLX** [AmperSoftware/TF-Source-2#68]
### Describe the bug

This affects Sniper's Scope & Ubercharge

### To Reproduce

1. Play Sniper or Medic
2. Notice the screen overlay shaders not drawing

### Expected behavior

Should draw as expected, either it's an easy fix or we should wait for FP shader merges that should come soon.

**Comment by rob5300** [comment]
This has now been resolved
