### ISSUE TITLE
The scattergun shoots above where you aim

### ISSUE THREAD

**Issue by Tryak03** [AmperSoftware/TF-Source-2#8]
### Describe the bug

The scattergun on scout shoots where the camera tilts up when you after you shoot, instead of shooting where the crosshair originally is. This means the bullets will shoot above where you're aiming.

### To Reproduce

1. Load any map
2. Spawn as scout and equip the Scattergun
3. Shoot at a wall
4. Notice that the bullets on average will be above your crosshair

### Expected behavior

The bullets should shoot where you're aiming before the camera tilts up, the camera tilt shouldn't affect your aim.

**Comment by Retr0-01** [comment]
This seems to be fixed at latest `dev`
