### ISSUE TITLE
Movement choppy when turning camera

### ISSUE THREAD

**Issue by Herotroll** [AmperSoftware/TF-Source-2#9]
### Describe the bug

Movement becomes choppy when combined with mouse movement.

### To Reproduce

Press one of the movement keys and move your mouse around.

### Expected behavior

Much chop.

### Media/Files

https://user-images.githubusercontent.com/50330035/187180696-aab59618-5c04-4864-a81a-69663f273978.mp4

### Additional context

I was hosting the server, so lag shouldn't play a role.

**Comment by Retr0-01** [comment]
This was fixed in https://github.com/AmperSoftware/sbox-FPS-SDK/commit/f2aad2a7095c299a03e14a7f144eaba72d79f4c8
