### ISSUE TITLE
Attacker should recieve different radius and damage from their fired rockets. (this is an actual thing that tf2 does)

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2#95]
### What can't you do?

In base TF2, some attributes only affect other players.

For example, the Direct Hit's decreased blast radius does not affect the person who fired the rocket.

### How would you like it to work?

There needs to be a way for the user to recieve unique values (such as for blast radius & damage).

TF2 only applies the attributes for other players, so maybe it works like disguises where players recieve different information from the server? I'm not well versed with networking.

### Additional context

I'm of course bringing up the Direct HIt because it is what I was working on when I discovered this quirk.
Here are some videos I recorded in base TF2 to show said quirk in action.

### ROCKET LAUNCHER

https://user-images.githubusercontent.com/91832803/230789378-b9872770-d837-40c2-ba32-b486ce36b62f.mp4

### DIRECT HIT

https://user-images.githubusercontent.com/91832803/230789566-25adafc7-a591-4c34-b106-9e67348eabf7.mp4
___

# TEAM FORTRESS: SOURCE 2

Another discovery I made is that TF:S2 rockets damages you from an additional 24 units away.

I remember reading about blast radiuses shooting a ray to the center of your hitbox in TF2 to see if it hit.

Does it check for overlapping hitboxes in TF:S2? If that is the case then it might be Soldier's hitbox radius contributing additional reach.

https://user-images.githubusercontent.com/91832803/230790150-58e5ff39-5ca2-4a6c-b573-112a35f812c5.mp4

**Comment by qualitykk** [comment]
So if im understanding this correctly this requires extending `RadiusDamageInfo` to allow you to either
A) Have a seperate radius field for self damage or
B) Have a seperate radius property which contains another `RadiusDamageInfo` just for self damage

Which one do you think would fit better for this situation?

**Comment by qualitykk** [comment]
Has this been addressed in #96?

**Comment by yourbadandimbest** [comment]
Yes
